### PR TITLE
Add test for claim for an application

### PR DESCRIPTION
**Pull request by baijum**
Ref. https://issues.redhat.com/browse/APPSVC-1297

### CODE REVIEW

**Review by filariow — DISMISSED** [review]
lgtm

**Comment by baijum** [comment]
> lgtm

rebased. Please approve again and merge.

**Comment by baijum** [comment]
> > lgtm
> 
> rebased. Please approve again and merge.

rebased again.  Please approve again and merge.

**Review by filariow — APPROVED** [review]
lgtm

**Pull request merged**
